version: '3.0'

services:
  back:
    container_name: as_back
    hostname: as_back
    image: as_back
    restart: unless-stopped
    networks:
      - lan
    volumes:
      - "./persistentData/db.sqlite3:/backend/db.sqlite3"
    command: >
      bash -c "source venv/bin/activate && (celery -A autoscoutapi beat -l info & celery -A autoscoutapi worker -l info & python3 manage.py makemigrations --noinput && python3 manage.py migrate && /usr/sbin/apache2ctl -D FOREGROUND)"

  rabbit:
    container_name: as_rabbitmq
    hostname: as_rabbitmq
    image: rabbitmq
    restart: unless-stopped
    networks:
      - lan

networks:
  lan:
    external: true
